package com.epam.forum.command;

public enum CommandName {
	LOGIN,
	REGISTRATION,
	VIEW_USER,
	VIEW_USER_BY_ID,
	SORT_USER_BY_ID,
	VIEW_USER_BY_USERNAME,
	LOGOUT,
	VIEW_TOPIC,
	VIEW_SECTION,
	LANGUAGE,
	VIEW_TOPIC_BY_HEADER	
}
