package com.epam.forum.command;

/**
 * The {@code CommandName} contains all commands
 * 
 * @author Andrey Shcherbin
 * @version 1.0
 * @since 2021-05-30
 *
 */
public enum CommandName {	
	EMPTY_COMMAND,
	SEARCH,
	GO_TO_LOGIN_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_HOME_PAGE,
	GO_TO_TOPIC_PAGE,
	GO_TO_SECTION_PAGE,
	LOGIN,
	REGISTRATION,		
	VIEW_SECTION,
	VIEW_SECTION_BY_ID,
	LANGUAGE,
	VIEW_TOPIC,
	VIEW_TOPIC_BY_HEADER,		
	VIEW_TOPIC_BY_ID,
	ACTIVATION,	
	LOGOUT,
	CREATE_POST,
	DELETE_POST,
	EDIT_POST,
	CREATE_TOPIC,
	GO_TO_NEW_TOPIC_PAGE,	
	DELETE_TOPIC,
	PIN_TOPIC,
	CLOSE_TOPIC,	
	CREATE_SECTION,
	DELETE_SECTION,
	GO_TO_NEW_SECTION_PAGE,
	GO_TO_ADMIN_HOME_PAGE,
	VIEW_USER,
	VIEW_USER_BY_ID,
	VIEW_USER_BY_USERNAME,
	CHANGE_ROLE,
	BAN_USER
}
