package com.epam.forum.command;

public enum CommandName {
	GO_TO_LOGIN_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_HOME_PAGE,	
	LOGIN,
	REGISTRATION,
	VIEW_USER,
	VIEW_USER_BY_ID,
	SORT_USER_BY_ID,
	VIEW_USER_BY_USERNAME,
	LOGOUT,
	VIEW_TOPIC,
	VIEW_SECTION,
	LANGUAGE,
	VIEW_TOPIC_BY_HEADER,
	VIEW_TOPIC_BY_SECTION,
	VIEW_TOPIC_BY_ID,
	CREATE_POST,
	DELETE_POST_BY_ID,
	EDIT_POST_BY_ID,
	ACTIVATION
}
